"use client";
import {useCallback,useEffect,useRef,useState} from "react";
type Drop={id:number;type:"pick"|"tnt";x:number;y:number;vx:number;vy:number;rot:number;vr:number;life:number;name:string};
type Cell={hp:number;max:number;ore:number;kind:number;crack:number};
const NAMES=["Ariuka","Temuulen","Anu","Bilguun","Naraa","Munkh","Saraa","You"],ORES=["COAL","COPPER","GOLD","LAPIS","DIAMOND","EMERALD"],COLORS=["#252a35","#c56f4d","#f4c83e","#2768d8","#31dbea","#39db78"];
export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null),drops=useRef<Drop[]>([]),grid=useRef<Cell[][]>([]),uid=useRef(0),frame=useRef(0),depthRef=useRef(0);
 const [score,setScore]=useState(0),[depth,setDepth]=useState(0),[combo,setCombo]=useState(1),[sound,setSound]=useState(false),[event,setEvent]=useState("PICKAXE RAIN"),[count,setCount]=useState([0,0,0,0,0,0]);
 const makeRow=useCallback((row:number)=>Array.from({length:8},(_,x)=>{const ore=Math.random()<.22?Math.min(5,Math.floor(row/7)+Math.floor(Math.random()*2)):-1,max=ore>=0?4+ore*2:3+Math.floor(row/8);return{hp:max,max,ore,kind:(x+row)%4,crack:0}}),[]);
 const spawn=useCallback((type:"pick"|"tnt"|"mega"="pick",name?:string)=>{const amount=type==="mega"?9:type==="tnt"?3:1;for(let i=0;i<amount;i++)drops.current.push({id:++uid.current,type:type==="mega"?"pick":type,x:75+Math.random()*300,y:-40-Math.random()*170,vx:(Math.random()-.5)*2.2,vy:1+Math.random()*2,rot:Math.random()*6.2,vr:(Math.random()-.5)*.16,life:900,name:name||NAMES[Math.floor(Math.random()*NAMES.length)]});setEvent(type==="mega"?"⚡ PICKAXE STORM!":type==="tnt"?"💥 TNT DROP!":"⛏ NEW PICKAXE")},[]);
 useEffect(()=>{grid.current=Array.from({length:13},(_,r)=>makeRow(r));const t=setInterval(()=>spawn("pick"),1250);return()=>clearInterval(t)},[makeRow,spawn]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;canvas.width=450;canvas.height=800;
  const hit=(d:Drop)=>{const top=285,row=Math.floor((d.y-top)/50),col=Math.floor(d.x/56.25);if(row<0||row>=grid.current.length||col<0||col>7)return false;const cell=grid.current[row]?.[col];if(!cell||cell.hp<=0)return false;const damage=d.type==="tnt"?8:1;cell.hp-=damage;cell.crack=1-cell.hp/cell.max;setScore(s=>s+damage*10);setCombo(c=>Math.min(99,c+1));if(cell.hp<=0){if(cell.ore>=0)setCount(old=>old.map((v,i)=>i===cell.ore?v+1:v));setScore(s=>s+100+(cell.ore+1)*80)}if(d.type==="tnt"){for(let ry=Math.max(0,row-1);ry<=Math.min(12,row+1);ry++)for(let cx=Math.max(0,col-1);cx<=Math.min(7,col+1);cx++){const c=grid.current[ry][cx];c.hp-=5;c.crack=1-c.hp/c.max}d.life=0}else{d.vy=-Math.abs(d.vy)*.48;d.vx+=(Math.random()-.5)*2;d.y=top+row*50-18;d.life-=90}return true};
  const drawDrop=(d:Drop)=>{ctx.save();ctx.translate(d.x,d.y);ctx.rotate(d.rot);ctx.lineWidth=6;ctx.strokeStyle="#70411f";if(d.type==="tnt"){ctx.fillStyle="#e53935";ctx.fillRect(-17,-20,34,40);ctx.fillStyle="#fff";ctx.fillRect(-17,-5,34,11);ctx.fillStyle="#111";ctx.font="bold 9px Arial";ctx.fillText("TNT",-10,4)}else{ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(0,24);ctx.stroke();ctx.strokeStyle="#b9e8ee";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-23,-16);ctx.quadraticCurveTo(0,-29,24,-15);ctx.stroke()}ctx.restore();ctx.font="bold 10px Arial";ctx.textAlign="center";ctx.fillStyle="#fff";ctx.shadowColor="#000";ctx.shadowBlur=3;ctx.fillText(d.name,d.x,d.y-30);ctx.shadowBlur=0};
  const loop=()=>{frame.current=requestAnimationFrame(loop);ctx.clearRect(0,0,450,800);const g=ctx.createLinearGradient(0,0,0,800);g.addColorStop(0,"#08172d");g.addColorStop(.36,"#163c63");g.addColorStop(.365,"#162235");g.addColorStop(1,"#080b16");ctx.fillStyle=g;ctx.fillRect(0,0,450,800);ctx.fillStyle="#ffffff08";for(let i=0;i<30;i++)ctx.fillRect((i*97)%450,(i*53)%270,2,2);const top=285;
   grid.current.forEach((row,r)=>row.forEach((c,x)=>{if(c.hp<=0)return;const px=x*56.25,py=top+r*50;ctx.fillStyle=["#59606b","#505965","#616873","#48525e"][c.kind];ctx.fillRect(px,py,56.25,50);ctx.strokeStyle="#252b35";ctx.strokeRect(px+.5,py+.5,55.25,49);ctx.fillStyle="#ffffff08";ctx.fillRect(px+5,py+5,18,7);if(c.ore>=0){ctx.fillStyle=COLORS[c.ore];ctx.fillRect(px+9,py+10,11,9);ctx.fillRect(px+33,py+25,14,11);ctx.fillRect(px+18,py+37,8,7)}if(c.crack>.15){ctx.strokeStyle=`rgba(10,12,17,${Math.min(.9,c.crack)})`;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px+28,py);ctx.lineTo(px+23,py+15);ctx.lineTo(px+35,py+26);ctx.lineTo(px+24,py+40);ctx.lineTo(px+30,py+50);ctx.stroke()}}));
   let cleared=0;for(const row of grid.current){if(row.every(c=>c.hp<=0))cleared++;else break}if(cleared){grid.current.splice(0,cleared);for(let i=0;i<cleared;i++)grid.current.push(makeRow(depthRef.current+13+i));depthRef.current+=cleared;setDepth(depthRef.current);setEvent(cleared>=2?"🔥 DOUBLE DEPTH!":"⬇ CAVE DESCENT")}
   for(const d of drops.current){d.vy=Math.min(d.vy+.16,8);d.x+=d.vx;d.y+=d.vy;d.rot+=d.vr;d.life--;if(d.x<15||d.x>435)d.vx*=-.8;if(d.y>265)hit(d);drawDrop(d)}drops.current=drops.current.filter(d=>d.life>0&&d.y<820)};loop();return()=>cancelAnimationFrame(frame.current)},[makeRow]);
 return <main className="shell"><section className="liveGame"><canvas ref={canvasRef}/><header><div className="live"><i/>LIVE</div><div className="metric"><small>SCORE</small><b>{score.toLocaleString()}</b></div><div className="metric"><small>DEPTH</small><b>{depth}m</b></div><button onClick={()=>setSound(v=>!v)}>{sound?"🔊":"🔇"}</button></header><div className="logo"><small>INTERACTIVE LIVE</small><strong>MINE <em>RUSH</em></strong><span>LIKE = PICKAXE　•　SUB = TNT</span></div><aside>{ORES.map((o,i)=><div key={o}><i style={{background:COLORS[i]}}/><span>{o}</span><b>{count[i]}</b></div>)}</aside><div className="event"><span>{event}</span><b>COMBO x{combo}</b></div><div className="bossMeter"><label>NEXT CAVE BOSS</label><div><i style={{width:`${(depth%25)*4}%`}}/></div><b>{25-depth%25}m</b></div><nav><button onClick={()=>spawn("pick","LIKE")}>👍<b>LIKE</b><small>+ PICKAXE</small></button><button onClick={()=>spawn("tnt","NEW SUB")}>🔔<b>SUB</b><small>+ TNT</small></button><button onClick={()=>spawn("mega","SUPER CHAT")}>⚡<b>STORM</b><small>9× PICKAXE</small></button></nav></section></main>
}
